var start = document.getElementById("start");
var shapes = document.getElementById("shapes");
var timeTaken = document.getElementById("timeTaken");
// all getElementById above this line... ... ...
var startTime = 0; //to store starting time...
var endTime; //to store ending time...
// all other variable declaration above this line... ... ...
//functionality interaction script below this line ... ... ...
// doDelayFun(); //get shapes after a delay...
start.onclick = function() {
	start.style.display = "none";
	doDelayFun(); //get shapes after a delay...
}
shapes.onclick = function() { //when shapes are clicked...
	shapes.style.display = "none";
	endTime = new Date().getTime(); //to get time that looks like 1489421263006 (ms)... //store the ending time...
	var x = (endTime-startTime)/1000; //to get the time difference b/w appearance and click...
	timeTaken.innerHTML = x;
	doDelayFun(); //get shapes after a delay...
}
// all function definitions below this line... ... ...
function getShapesFun() { //function to generate shapes...
	shapes.style.width = Math.round(80*Math.random() + 50) + "px"; //width must be b/w 50 and 50+80...
	shapes.style.height = Math.round(80*Math.random() + 50) + "px"; //height must be b/w 50 and 50+80...
	shapes.style.backgroundColor = getColorFun(); //get random bg color... call getColorFun();
	shapes.style.top = Math.round(550*Math.random() + 10) + "px"; //position from top b/w 10 and 550...
	shapes.style.left = Math.round(750*Math.random() + 10) + "px"; //position from left b/w 10 and 750...
	var x = Math.random();
	if (x<0.2) { //on an avg 20% of times border-radius is 50%...
		shapes.style.borderRadius = "50%";
	} else if (x>0.2 && x<0.4) { //on an avg 20% of times border-radius is 40%...
		shapes.style.borderRadius = "40%";
	} else if (x>0.4 && x<0.6) { //on an avg 20% of times border-radius is 30%...
		shapes.style.borderRadius = "30%";
	} else if (x>0.6 && x<0.8) { //on an avg 20% of times border-radius is 10%...
		shapes.style.borderRadius = "10%";
	} else { //on an avg 20% of times no border-radius...
		shapes.style.borderRadius = "0";
	}
	shapes.style.display = "block";
	startTime = new Date().getTime(); //store the starting time...
}
function getColorFun() { //function to generate random hex colors...
	var hexCodes = "0123456789ABCDEF".split(""); //get array of hex codes...
	var ranColor = "#";
	for (var i=1; i<=6; i++) {
		var x = Math.floor(16*Math.random()); //numbers b/w 0 and 15...
		ranColor += hexCodes[x];
	}
	return ranColor;
}
function doDelayFun() { //function to get a delay in shapes appearing on screen...
	setTimeout (getShapesFun, Math.floor(2001*Math.random())); //happen randomly before 2 seconds...
}